#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unknown_lints)]
#![allow(ellipsis_inclusive_range_patterns)]
// These files are generated by rust-peg 0.6. Applying Clippy's structural
// rewrites to the generated state machine produces invalid Rust; keep the
// generated output byte-stable and lint the handwritten parser API around it.
#![allow(
    clippy::blocks_in_conditions,
    clippy::flat_map_identity,
    clippy::len_zero,
    clippy::needless_lifetimes,
    clippy::redundant_field_names,
    clippy::single_match,
    clippy::type_complexity,
    clippy::unit_arg
)]

include!("prelude.rs");
include!("identifiers_and_integers.rs");
include!("floats_and_strings.rs");
include!("primary_and_generic.rs");
include!("postfix_and_compound.rs");
include!("unary_sizeof_alignof.rs");
include!("casts_and_binary.rs");
include!("conditional_assignment_and_expression.rs");
include!("declarations_entry.rs");
include!("init_declarators_and_storage.rs");
include!("type_specifiers.rs");
include!("structs.rs");
include!("specifier_qualifiers.rs");
include!("enums_and_qualifiers.rs");
include!("function_and_alignment_specifiers.rs");
include!("declarators.rs");
include!("pointers_parameters_and_typenames.rs");
include!("abstract_declarators.rs");
include!("typedefs_initializers_and_asserts.rs");
include!("statements_labels_and_selection.rs");
include!("statements_iteration_and_jump.rs");
include!("translation_units_and_functions.rs");
include!("attributes.rs");
include!("availability_and_asm_labels.rs");
include!("asm_statements.rs");
include!("gnu_keyword_and_offsetof.rs");
include!("typeof_and_ts18661.rs");
include!("public_api.rs");
